### ISSUE TITLE
error in building reasoner when running docker compose for the first time

### ISSUE THREAD

**Issue by jli113** [gtfierro/mortar#10]
os: ubuntu 20.04 64
docker version: 20.10.13
docker compose version: 1.29.2
What I did was, clone--change username and passwd--docker-compose

error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/oxilangtag-0.1.3/src/lib.rs:1:10
  |
1 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling wyz v0.2.0
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
   Compiling regex-syntax v0.6.25
error: could not compile `oxilangtag`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
ERROR: Service 'reasoner' failed to build : Build failed

**Comment by gtfierro** [comment]
I updated the `reasoner` dependencies and can't reproduce this error; can you do a `git pull` and try again?

**Comment by jli113** [comment]
Sure, I removed the local folder and cloned the latest version.
This time I didn't change anything, same error

docker-compose up
Building reasoner
Sending build context to Docker daemon  14.16MB
Step 1/8 : FROM rust:1.53.0 AS builder
 ---> 1ecb70e16851
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> c874b02225ea
Step 3/8 : COPY reasoner .
 ---> de05dd3f268b
Step 4/8 : RUN cargo build --release
 ---> Running in a492a8e489f6
    Updating crates.io index
 Downloading crates ...
  Downloaded httpdate v0.3.2
  Downloaded pin-project v1.0.10
  Downloaded log v0.4.16
  Downloaded pin-utils v0.1.0
  Downloaded futures-macro v0.3.21
  Downloaded futures-task v0.3.21
  Downloaded pin-project-lite v0.2.8
  Downloaded arrayvec v0.5.2
  Downloaded pin-project-internal v0.4.29
  Downloaded tower-service v0.3.1
  Downloaded futures-sink v0.3.21
  Downloaded futures-core v0.3.21
  Downloaded tracing v0.1.32
  Downloaded hyper v0.13.10
  Downloaded unicode-normalization v0.1.19
  Downloaded atty v0.2.14
  Downloaded futures-executor v0.3.21
  Downloaded socket2 v0.3.19
  Downloaded static_assertions v1.1.0
  Downloaded siphasher v0.3.10
  Downloaded subtle v2.4.1
  Downloaded sha-1 v0.9.8
  Downloaded slab v0.4.5
  Downloaded tinyvec_macros v0.1.0
  Downloaded h2 v0.2.7
  Downloaded termcolor v1.1.3
  Downloaded smallvec v1.8.0
  Downloaded instant v0.1.12
  Downloaded bitflags v1.3.2
  Downloaded serde v1.0.136
  Downloaded once_cell v1.10.0
  Downloaded serde_derive v1.0.136
  Downloaded serde_json v1.0.79
  Downloaded tempfile v3.3.0
  Downloaded byteorder v0.5.3
  Downloaded rand v0.8.5
  Downloaded bytes v0.5.6
  Downloaded funty v1.1.0
  Downloaded tinyvec v1.5.1
  Downloaded crypto-common v0.1.3
  Downloaded futures v0.3.21
  Downloaded headers-core v0.2.0
  Downloaded http-body v0.3.1
  Downloaded syn v1.0.90
  Downloaded fastrand v1.7.0
  Downloaded autocfg v1.1.0
  Downloaded fnv v1.0.7
  Downloaded httpdate v1.0.2
  Downloaded digest v0.10.3
  Downloaded futures-channel v0.3.21
  Downloaded block-buffer v0.10.2
  Downloaded datafrog v2.0.1
  Downloaded humantime v1.3.0
  Downloaded matches v0.1.9
  Downloaded hmac v0.9.0
  Downloaded radium v0.5.3
  Downloaded phf v0.8.0
  Downloaded generic-array v0.14.5
  Downloaded input_buffer v0.3.1
  Downloaded rand_chacha v0.2.2
  Downloaded sha2 v0.9.9
  Downloaded tokio-util v0.3.1
  Downloaded tokio-macros v0.2.6
  Downloaded itertools v0.8.2
  Downloaded tinytemplate v1.2.1
  Downloaded bitvec v0.19.6
  Downloaded env_logger v0.7.1
  Downloaded fs2 v0.4.3
  Downloaded tap v1.0.1
  Downloaded getrandom v0.1.16
  Downloaded block-buffer v0.9.0
  Downloaded digest v0.9.0
  Downloaded getrandom v0.2.6
  Downloaded try-lock v0.2.3
  Downloaded indexmap v1.8.1
  Downloaded twoway v0.1.8
  Downloaded tokio-tungstenite v0.11.0
  Downloaded cfg-if v0.1.10
  Downloaded either v1.6.1
  Downloaded cfg-if v1.0.0
  Downloaded hashbrown v0.11.2
  Downloaded remove_dir_all v0.5.3
  Downloaded memoffset v0.6.5
  Downloaded itoa v1.0.1
  Downloaded byteorder v1.4.3
  Downloaded scopeguard v1.1.0
  Downloaded mime v0.3.16
  Downloaded rand_core v0.6.3
  Downloaded crossbeam-epoch v0.9.8
  Downloaded mime_guess v2.0.4
  Downloaded crossbeam-utils v0.8.8
  Downloaded typenum v1.15.0
  Downloaded unicase v2.6.0
  Downloaded opaque-debug v0.3.0
  Downloaded memchr v2.4.1
  Downloaded dtoa v0.4.8
  Downloaded unicode-bidi v0.3.7
  Downloaded hex v0.4.3
  Downloaded tracing-core v0.1.23
  Downloaded fxhash v0.2.1
  Downloaded http v0.2.6
  Downloaded itoa v0.4.8
  Downloaded headers v0.3.7
  Downloaded regex v1.5.5
  Downloaded scoped-tls v1.0.0
  Downloaded json-event-parser v0.1.1
  Downloaded tracing-futures v0.2.5
  Downloaded md-5 v0.9.1
  Downloaded lasso v0.5.1
  Downloaded idna v0.2.3
  Downloaded tokio-postgres v0.5.5
  Downloaded regex-syntax v0.6.25
  Downloaded stringprep v0.1.2
  Downloaded mio v0.6.23
  Downloaded num_cpus v1.13.1
  Downloaded mio-uds v0.6.8
  Downloaded net2 v0.2.37
  Downloaded safemem v0.3.3
  Downloaded utf-8 v0.7.6
  Downloaded urlencoding v1.3.3
  Downloaded buf_redux v0.8.4
  Downloaded cpufeatures v0.2.2
  Downloaded rand_core v0.5.1
  Downloaded lazy_static v1.4.0
  Downloaded lock_api v0.4.7
  Downloaded want v0.3.0
  Downloaded base64 v0.12.3
  Downloaded unicode-xid v0.2.2
  Downloaded multipart v0.17.1
  Downloaded ahash v0.7.6
  Downloaded oxigraph v0.2.5
  Downloaded md5 v0.7.0
  Downloaded url v2.2.2
  Downloaded aho-corasick v0.7.18
  Downloaded nom v6.1.2
  Downloaded base64 v0.13.0
  Downloaded warp v0.2.5
  Downloaded rio_api v0.5.3
  Downloaded iovec v0.1.4
  Downloaded httparse v1.6.0
  Downloaded wyz v0.2.0
  Downloaded bytes v1.1.0
  Downloaded peg-macros v0.7.0
  Downloaded form_urlencoded v1.0.1
  Downloaded dashmap v4.0.2
  Downloaded futures-io v0.3.21
  Downloaded bb8 v0.5.2
  Downloaded futures-util v0.3.21
  Downloaded crc32fast v1.3.2
  Downloaded tungstenite v0.11.1
  Downloaded quick-xml v0.22.0
  Downloaded sha-1 v0.10.0
  Downloaded percent-encoding v2.1.0
  Downloaded parking_lot_core v0.8.5
  Downloaded ppv-lite86 v0.2.16
  Downloaded quick-error v1.2.3
  Downloaded oxilangtag v0.1.3
  Downloaded phf_shared v0.8.0
  Downloaded peg-runtime v0.7.0
  Downloaded oxiri v0.1.1
  Downloaded pin-project-internal v1.0.10
  Downloaded pin-project-lite v0.1.12
  Downloaded pin-project v0.4.29
  Downloaded bb8-postgres v0.5.0
  Downloaded serde_urlencoded v0.6.1
  Downloaded rand v0.7.3
  Downloaded postgres-types v0.1.3
  Downloaded proc-macro2 v1.0.36
  Downloaded pyo3-build-config v0.15.1
  Downloaded roaring v0.5.2
  Downloaded rdf v0.1.4
  Downloaded rio_turtle v0.5.3
  Downloaded postgres-protocol v0.5.3
  Downloaded peg v0.7.0
  Downloaded parking_lot v0.11.2
  Downloaded rand_chacha v0.3.1
  Downloaded async-trait v0.1.53
  Downloaded version_check v0.9.4
  Downloaded ryu v1.0.9
  Downloaded crypto-mac v0.9.1
  Downloaded rio_xml v0.5.3
  Downloaded fallible-iterator v0.2.0
  Downloaded quote v1.0.17
  Downloaded disjoint-sets v0.4.2
  Downloaded tokio v0.2.25
  Downloaded sled v0.34.7
  Downloaded lexical-core v0.7.6
  Downloaded libc v0.2.121
  Downloaded reasonable v0.1.53
  Downloaded farmhash v1.1.5
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling libc v0.2.121
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.90
   Compiling memchr v2.4.1
   Compiling autocfg v1.1.0
   Compiling typenum v1.15.0
   Compiling log v0.4.16
   Compiling lazy_static v1.4.0
   Compiling fnv v1.0.7
   Compiling scopeguard v1.1.0
   Compiling parking_lot_core v0.8.5
   Compiling futures-core v0.3.21
   Compiling smallvec v1.8.0
   Compiling slab v0.4.5
   Compiling bytes v0.5.6
   Compiling ppv-lite86 v0.2.16
   Compiling tinyvec_macros v0.1.0
   Compiling cpufeatures v0.2.2
   Compiling getrandom v0.1.16
   Compiling itoa v1.0.1
   Compiling futures-channel v0.3.21
   Compiling futures-sink v0.3.21
   Compiling pin-project-lite v0.2.8
   Compiling futures-task v0.3.21
   Compiling opaque-debug v0.3.0
   Compiling cfg-if v0.1.10
   Compiling bytes v1.1.0
   Compiling unicode-bidi v0.3.7
   Compiling byteorder v1.4.3
   Compiling futures-util v0.3.21
   Compiling futures-io v0.3.21
   Compiling pin-utils v0.1.0
   Compiling once_cell v1.10.0
   Compiling pin-project-lite v0.1.12
   Compiling percent-encoding v2.1.0
   Compiling serde_derive v1.0.136
   Compiling matches v0.1.9
   Compiling httparse v1.6.0
   Compiling ryu v1.0.9
   Compiling serde v1.0.136
   Compiling subtle v2.4.1
   Compiling crossbeam-utils v0.8.8
   Compiling siphasher v0.3.10
   Compiling radium v0.5.3
   Compiling bitflags v1.3.2
   Compiling base64 v0.13.0
   Compiling pyo3-build-config v0.15.1
   Compiling async-trait v0.1.53
   Compiling crc32fast v1.3.2
   Compiling lexical-core v0.7.6
   Compiling pin-project-internal v0.4.29
   Compiling quick-error v1.2.3
   Compiling serde_json v1.0.79
   Compiling funty v1.1.0
   Compiling regex-syntax v0.6.25
   Compiling mime v0.3.16
   Compiling md5 v0.7.0
   Compiling rio_api v0.5.3
   Compiling oxilangtag v0.1.3
   Compiling oxiri v0.1.1
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/oxilangtag-0.1.3/src/lib.rs:1:10
  |
1 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling fallible-iterator v0.2.0
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `oxilangtag`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
ERROR: Service 'reasoner' failed to build : Build failed

**Comment by gtfierro** [comment]
~~Very strange...I'm having a hard time reproducing this error. For some reason my local install is attempting to install `oxilangtag==0.1.2` rather than `oxilangtag==0.1.3` like you have above.~~

~~Do you get the same error when you run `docker-compose build --no-cache reasoner`?~~

Nevermind -- just reproduced the error! I'll see how I can mitigate

**Comment by gtfierro** [comment]
@jli113 can you pull and retry? Bumping the version of rust needed to build the reasoner seems to fix the issue for me

**Comment by jli113** [comment]
docker-compose succeeded, but it's having another error:
mortar_jupyter-notebook_1 exited with code 1
mortar_reasoner_1 exited with code 1

WARNING: Image for service jupyter-notebook was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating mortar_cadvisor_1         ... done
Creating mortar_pg_1               ... done
Creating mortar_mortar-server_1    ... done
Creating mortar_jupyter-notebook_1 ... done
Creating mortar_reasoner_1         ... done
Creating mortar_prometheus_1       ... done
Creating mortar_nginx_1            ... done
Attaching to mortar_mortar-server_1, mortar_cadvisor_1, mortar_jupyter-notebook_1, mortar_pg_1, mortar_reasoner_1, mortar_prometheus_1, mortar_nginx_1
cadvisor_1          | W0401 07:26:15.176735       1 manager.go:288] Could not configure a source for OOM detection, disabling OOM events: open /dev/kmsg: no such file or directory
jupyter-notebook_1  | WARNING: JUPYTER_ENABLE_LAB is ignored, use DOCKER_STACKS_JUPYTER_CMD if you want to change the command used to start the server
jupyter-notebook_1  | Entered start.sh with args: jupyter lab --NotebookApp.token=test-secret --NotebookApp.allow_origin=*
jupyter-notebook_1  | Executing the command: jupyter lab --NotebookApp.token=test-secret --NotebookApp.allow_origin=*
nginx_1             | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1             | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
jupyter-notebook_1  | Traceback (most recent call last):
jupyter-notebook_1  |   File "/opt/conda/bin/jupyter-lab", line 6, in <module>
mortar-server_1     | 2022-04-01T07:26:15Z	warn	mortar	database/database.go:96	Failed to connect to database (failed to connect to `host=pg user=mbt database=mortar`: dial error (dial tcp 172.23.0.4:5432: connect: connection refused)); retrying in 5 seconds
pg_1                | The files belonging to this database system will be owned by user "postgres".
pg_1                | This user must also own the server process.
pg_1                | 
jupyter-notebook_1  |     from jupyterlab.labapp import main
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jupyterlab/labapp.py", line 13, in <module>
jupyter-notebook_1  |     from jupyter_server.serverapp import flags
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 39, in <module>
prometheus_1        | ts=2022-04-01T07:26:15.607Z caller=main.go:479 level=info msg="No time or size retention was set so using the default time retention" duration=15d
nginx_1             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
jupyter-notebook_1  |     from jinja2 import Environment, FileSystemLoader
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
pg_1                | The database cluster will be initialized with locale "en_US.utf8".
pg_1                | The default database encoding has accordingly been set to "UTF8".
pg_1                | The default text search configuration will be set to "english".
pg_1                | 
pg_1                | Data page checksums are disabled.
pg_1                | 
jupyter-notebook_1  |     from .environment import Environment
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
jupyter-notebook_1  |     from .defaults import BLOCK_END_STRING
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
prometheus_1        | ts=2022-04-01T07:26:15.607Z caller=main.go:516 level=info msg="Starting Prometheus" version="(version=2.34.0, branch=HEAD, revision=881111fec4332c33094a6fb2680c71fffc427275)"
jupyter-notebook_1  |     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
nginx_1             | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
pg_1                | fixing permissions on existing directory /data ... ok
jupyter-notebook_1  |     from markupsafe import soft_unicode
jupyter-notebook_1  | ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/conda/lib/python3.9/site-packages/markupsafe/__init__.py)
prometheus_1        | ts=2022-04-01T07:26:15.607Z caller=main.go:521 level=info build_context="(go=go1.17.8, user=root@121ad7ea5487, date=20220315-15:18:00)"
reasoner_1          | Loaded files
prometheus_1        | ts=2022-04-01T07:26:15.607Z caller=main.go:522 level=info host_details="(Linux 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 7a1bc40c4a92 (none))"
prometheus_1        | ts=2022-04-01T07:26:15.607Z caller=main.go:523 level=info fd_limits="(soft=1048576, hard=1048576)"
reasoner_1          | Error: Error { kind: Connect, cause: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) }
pg_1                | creating subdirectories ... ok
prometheus_1        | ts=2022-04-01T07:26:15.607Z caller=main.go:524 level=info vm_limits="(soft=unlimited, hard=unlimited)"
nginx_1             | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx_1             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
pg_1                | selecting dynamic shared memory implementation ... posix
prometheus_1        | ts=2022-04-01T07:26:15.609Z caller=web.go:540 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
prometheus_1        | ts=2022-04-01T07:26:15.610Z caller=main.go:937 level=info msg="Starting TSDB ..."
pg_1                | selecting default max_connections ... 100
nginx_1             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
prometheus_1        | ts=2022-04-01T07:26:15.610Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
nginx_1             | /docker-entrypoint.sh: Configuration complete; ready for start up
pg_1                | selecting default shared_buffers ... 128MB
prometheus_1        | ts=2022-04-01T07:26:15.613Z caller=head.go:493 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
prometheus_1        | ts=2022-04-01T07:26:15.613Z caller=head.go:536 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=1.91µs
prometheus_1        | ts=2022-04-01T07:26:15.613Z caller=head.go:542 level=info component=tsdb msg="Replaying WAL, this may take a while"
pg_1                | selecting default time zone ... Etc/UTC
prometheus_1        | ts=2022-04-01T07:26:15.613Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
prometheus_1        | ts=2022-04-01T07:26:15.613Z caller=head.go:619 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=31.748µs wal_replay_duration=175.187µs total_replay_duration=227.503µs
prometheus_1        | ts=2022-04-01T07:26:15.614Z caller=main.go:958 level=info fs_type=EXT4_SUPER_MAGIC
prometheus_1        | ts=2022-04-01T07:26:15.614Z caller=main.go:961 level=info msg="TSDB started"
prometheus_1        | ts=2022-04-01T07:26:15.614Z caller=main.go:1142 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
pg_1                | creating configuration files ... ok
pg_1                | running bootstrap script ... ok
prometheus_1        | ts=2022-04-01T07:26:15.615Z caller=main.go:1179 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=462.382µs db_storage=613ns remote_storage=1.195µs web_handler=377ns query_engine=574ns scrape=207.462µs scrape_sd=40.873µs notify=726ns notify_sd=1.818µs rules=904ns tracing=4.12µs
prometheus_1        | ts=2022-04-01T07:26:15.615Z caller=main.go:910 level=info msg="Server is ready to receive web requests."
pg_1                | performing post-bootstrap initialization ... ok
pg_1                | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
pg_1                | You can change this by editing pg_hba.conf or using the option -A, or
pg_1                | --auth-local and --auth-host, the next time you run initdb.
pg_1                | ok
pg_1                | 
pg_1                | 
pg_1                | Success. You can now start the database server using:
pg_1                | 
pg_1                |     pg_ctl -D /data/ -l logfile start
pg_1                | 
pg_1                | waiting for server to start....2022-04-01 07:26:16.005 UTC [49] LOG:  starting PostgreSQL 12.10 (Debian 12.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pg_1                | 2022-04-01 07:26:16.010 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pg_1                | 2022-04-01 07:26:16.030 UTC [50] LOG:  database system was shut down at 2022-04-01 07:26:15 UTC
pg_1                | 2022-04-01 07:26:16.040 UTC [49] LOG:  database system is ready to accept connections
pg_1                |  done
pg_1                | server started
pg_1                | CREATE DATABASE
pg_1                | 
pg_1                | 
pg_1                | /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/001_install.sh
pg_1                | waiting for server to shut down....2022-04-01 07:26:16.236 UTC [49] LOG:  received fast shutdown request
pg_1                | 2022-04-01 07:26:16.238 UTC [49] LOG:  aborting any active transactions
pg_1                | 2022-04-01 07:26:16.239 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
pg_1                | 2022-04-01 07:26:16.239 UTC [51] LOG:  shutting down
pg_1                | 2022-04-01 07:26:16.251 UTC [49] LOG:  database system is shut down
pg_1                |  done
pg_1                | server stopped
pg_1                | waiting for server to start....2022-04-01 07:26:16.353 UTC [77] LOG:  starting PostgreSQL 12.10 (Debian 12.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pg_1                | 2022-04-01 07:26:16.355 UTC [77] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pg_1                | 2022-04-01 07:26:16.395 UTC [78] LOG:  database system was shut down at 2022-04-01 07:26:16 UTC
pg_1                | 2022-04-01 07:26:16.400 UTC [77] LOG:  database system is ready to accept connections
pg_1                | 2022-04-01 07:26:16.400 UTC [84] LOG:  TimescaleDB background worker launcher connected to shared catalogs
pg_1                |  done
pg_1                | server started
pg_1                | 2022-04-01 07:26:16.685 UTC [96] WARNING:  
pg_1                | 	WELCOME TO
pg_1                | 	 _____ _                               _     ____________  
pg_1                | 	|_   _(_)                             | |    |  _  \ ___ \ 
pg_1                | 	  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
pg_1                | 	  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
pg_1                | 	  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
pg_1                | 	  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
pg_1                | 	               Running version 2.6.0
pg_1                | 	For more information on TimescaleDB, please visit the following links:
pg_1                | 	
pg_1                | 	 1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
pg_1                | 	 2. API reference documentation: https://docs.timescale.com/api/latest
pg_1                | 	 3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts
pg_1                | 	
pg_1                | 	Note: TimescaleDB collects anonymous reports to better understand and assist our users.
pg_1                | 	For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.
pg_1                | 	
pg_1                | 2022-04-01 07:26:16.685 UTC [96] CONTEXT:  PL/pgSQL function inline_code_block line 12 at RAISE
pg_1                | WARNING:  
pg_1                | WELCOME TO
pg_1                |  _____ _                               _     ____________  
pg_1                | |_   _(_)                             | |    |  _  \ ___ \ 
pg_1                |   | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
pg_1                |   | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
pg_1                |   | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
pg_1                |   |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
pg_1                |                Running version 2.6.0
pg_1                | For more information on TimescaleDB, please visit the following links:
pg_1                | 
pg_1                |  1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
pg_1                |  2. API reference documentation: https://docs.timescale.com/api/latest
pg_1                |  3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts
pg_1                | 
pg_1                | Note: TimescaleDB collects anonymous reports to better understand and assist our users.
pg_1                | For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.
pg_1                | 
pg_1                | CREATE EXTENSION
pg_1                | 
pg_1                | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/002_setup.sql
pg_1                | CREATE TABLE
pg_1                | CREATE INDEX
pg_1                | CREATE TABLE
pg_1                | CREATE INDEX
pg_1                |  hypertable_id | schema_name | table_name | created 
pg_1                | ---------------+-------------+------------+---------
pg_1                |              1 | public      | data       | t
pg_1                | (1 row)
pg_1                | 
pg_1                | ALTER TABLE
pg_1                |  add_compression_policy 
pg_1                | ------------------------
pg_1                |                    1000
pg_1                | (1 row)
pg_1                | 
pg_1                | CREATE VIEW
pg_1                | psql:/docker-entrypoint-initdb.d/002_setup.sql:47: NOTICE:  continuous aggregate "hourly_summaries" is already up-to-date
pg_1                | CREATE MATERIALIZED VIEW
pg_1                |  add_continuous_aggregate_policy 
pg_1                | ---------------------------------
pg_1                |                             1001
pg_1                | (1 row)
pg_1                | 
pg_1                | CREATE TABLE
mortar_jupyter-notebook_1 exited with code 1
mortar_reasoner_1 exited with code 1
pg_1                | CREATE INDEX
pg_1                | CREATE VIEW
pg_1                | CREATE FUNCTION
pg_1                | CREATE TRIGGER
pg_1                | CREATE EXTENSION
pg_1                | CREATE TABLE
pg_1                | CREATE TABLE
pg_1                | CREATE FUNCTION
pg_1                | CREATE FUNCTION
pg_1                | CREATE FUNCTION
pg_1                | CREATE FUNCTION
pg_1                | CREATE FUNCTION
pg_1                | CREATE FUNCTION
pg_1                | 
pg_1                | 
pg_1                | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/003_backfill.sql
pg_1                | CREATE FUNCTION
pg_1                | CREATE PROCEDURE
pg_1                | CREATE PROCEDURE
pg_1                | CREATE FUNCTION
pg_1                | CREATE PROCEDURE
pg_1                | 
pg_1                | 
pg_1                | 2022-04-01 07:26:16.872 UTC [77] LOG:  received fast shutdown request
pg_1                | waiting for server to shut down....2022-04-01 07:26:16.874 UTC [77] LOG:  aborting any active transactions
pg_1                | 2022-04-01 07:26:16.874 UTC [97] LOG:  terminating TimescaleDB job scheduler due to administrator command
pg_1                | terminating TimescaleDB background worker launcher due to administrator command2022-04-01 07:26:16.874 UTC [84] FATAL:  terminating connection due to administrator command
pg_1                | 2022-04-01 07:26:16.874 UTC [97] FATAL:  terminating connection due to administrator command
pg_1                | 2022-04-01 07:26:16.874 UTC [99] LOG:  terminating TimescaleDB background job "Telemetry Reporter [1]" due to administrator command
pg_1                | 2022-04-01 07:26:16.874 UTC [97] LOG:  terminating TimescaleDB job scheduler due to administrator command
pg_1                | 2022-04-01 07:26:16.874 UTC [99] LOG:  terminating TimescaleDB background job "Telemetry Reporter [1]" due to administrator command
pg_1                | 2022-04-01 07:26:16.874 UTC [99] FATAL:  terminating connection due to administrator command
pg_1                | 2022-04-01 07:26:16.875 UTC [77] LOG:  background worker "logical replication launcher" (PID 85) exited with exit code 1
pg_1                | 2022-04-01 07:26:16.875 UTC [77] LOG:  background worker "TimescaleDB Background Worker Launcher" (PID 84) exited with exit code 1
pg_1                | 2022-04-01 07:26:16.875 UTC [77] LOG:  background worker "Telemetry Reporter [1]" (PID 99) exited with exit code 1
pg_1                | 2022-04-01 07:26:16.875 UTC [77] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 97) exited with exit code 1
pg_1                | 2022-04-01 07:26:16.875 UTC [79] LOG:  shutting down
pg_1                | 2022-04-01 07:26:16.922 UTC [77] LOG:  database system is shut down
pg_1                |  done
pg_1                | server stopped
pg_1                | 
pg_1                | PostgreSQL init process complete; ready for start up.
pg_1                | 
pg_1                | 2022-04-01 07:26:17.003 UTC [1] LOG:  starting PostgreSQL 12.10 (Debian 12.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pg_1                | 2022-04-01 07:26:17.004 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pg_1                | 2022-04-01 07:26:17.004 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pg_1                | 2022-04-01 07:26:17.007 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pg_1                | 2022-04-01 07:26:17.033 UTC [118] LOG:  database system was shut down at 2022-04-01 07:26:16 UTC
pg_1                | 2022-04-01 07:26:17.038 UTC [1] LOG:  database system is ready to accept connections
pg_1                | 2022-04-01 07:26:17.039 UTC [124] LOG:  TimescaleDB background worker launcher connected to shared catalogs
pg_1                | 2022-04-01 07:26:17.058 UTC [129] LOG:  refreshing continuous aggregate "hourly_summaries" in window [ 4714-11-24 00:00:00+00 BC, 2022-04-01 06:00:00+00 ]
jupyter-notebook_1  | Traceback (most recent call last):
jupyter-notebook_1  |   File "/opt/conda/bin/jupyter-lab", line 6, in <module>
jupyter-notebook_1  |     from jupyterlab.labapp import main
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jupyterlab/labapp.py", line 13, in <module>
jupyter-notebook_1  |     from jupyter_server.serverapp import flags
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 39, in <module>
jupyter-notebook_1  |     from jinja2 import Environment, FileSystemLoader
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
jupyter-notebook_1  |     from .environment import Environment
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
jupyter-notebook_1  |     from .defaults import BLOCK_END_STRING
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
jupyter-notebook_1  |     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
jupyter-notebook_1  |   File "/opt/conda/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
jupyter-notebook_1  |     from markupsafe import soft_unicode
jupyter-notebook_1  | ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/conda/lib/python3.9/site-packages/markupsafe/__init__.py)
mortar_jupyter-notebook_1 exited with code 1

**Comment by gtfierro** [comment]
This looks to be a dependency issue; I've pushed some changes and it looks like this has gone away. Can you pull and rebuild?

**Comment by jli113** [comment]
Causing another issue:
Building mortar-server
error checking context: 'can't stat '/home/r2d2/mortar/pg-data''.
ERROR: Service 'mortar-server' failed to build : Build failed

**Comment by jli113** [comment]
**Somehow, it's still not working.** 
1. These errors happened when building jupyter-notebook:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.22.3 which is incompatible.
**Along with a warning**:
WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

**After setting the numpy version "numpy<1.22,>=1.18", still got the error:**
[TrustNotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
Signing notebook: load_data_example.ipynb
Signing notebook: query_data_example.ipynb
Removing intermediate container 588396b5820c
 ---> edd107525e8c
Successfully built edd107525e8c
Successfully tagged mortar_jupyter-notebook:latest
WARNING: Image for service jupyter-notebook was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating mortar_jupyter-notebook_1 ... 
Creating mortar_jupyter-notebook_1 ... error
Creating mortar_pg_1               ... 
Creating mortar_cadvisor_1         ... 
WARNING: Host is already in use by another container

ERROR: for mortar_jupyter-notebook_1  Cannot start service jupyter-notebook: driCreating mortar_mortar-server_1    ... done
Creating mortar_pg_1               ... done
Creating mortar_cadvisor_1         ... done
Creating mortar_reasoner_1         ... done
Creating mortar_prometheus_1       ... done
Creating mortar_nginx_1            ... done

ERROR: for jupyter-notebook  Cannot start service jupyter-notebook: driver failed programming external connectivity on endpoint mortar_jupyter-notebook_1 (c20b28913cfc62eaf97801b2e4199634f30e7d6f37bf800baf71346015edbf13): Error starting userland proxy: listen tcp4 127.0.0.1:8888: bind: address already in use
ERROR: Encountered errors while bringing up the project.
